<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Ops;
use Neoan3\Core\Unicore;

class Start extends Unicore {
    private $components = ['start'];
    function init(){
        $this->uni('ideahub')
            ->callback($this,'setup')
            ->hook('main','start')
             ->output();
    }

    function setup($frame){
        foreach ($this->components as $component){
            $frame->vueComponent($component);
        }
    }



}
