<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Ops;
use Neoan3\Apps\Db;
use Neoan3\Apps\DbException;
use Neoan3\Apps\Session;
use Neoan3\Core\Unicore;

/**
 * Class Start
 *
 * @package Neoan3\Components
 */
class Start extends Unicore {
    /**
     * @var array
     */
    private $components = ['registerForm', 'register','start'];

    /**
     *
     */
    function init(){
        $this->uni('ideahub')
            ->callback($this,'setup')
            ->hook('main','start')
            ->output();
    }

    /**
     * @param $frame
     */
    function setup($frame){
        foreach ($this->components as $component){
            $frame->vueComponent($component);
        }
    }

    function newSession($userId){
        Session::login($userId);
    }


}
