<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;
use Neoan3\Core\RouteException;
use Neoan3\Frame\Ideahub;
use Neoan3\Model\UserModel;

class Register extends Ideahub {
    /**
     * @param $newUser
     *
     * @throws \Neoan3\Apps\DbException
     * @throws RouteException
     */
    function postRegister($newUser){
        if(!isset($newUser['email']) || !isset($newUser['password'])){
            throw new RouteException('missing values', 401);
        }

        $existingUser = UserModel::find(['email'=>$newUser['email']]);
        if(!empty($existingUser)){
            throw new RouteException('already registered', 403);
        }
        $registeredUser = UserModel::register($newUser['email'],$newUser['password']);
        return ['registration'=>'successful'];
    }

}
