<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Home extends Unicore {
    function init(){
        $this->uni('ideahub')->hook('main','home')->output();
    }

}
