<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;

class Home extends Unicore {
    private $components = ['home'];

    function init(){
        $this->uni('ideahub')
            ->callback($this,'setup')
             ->hook('main','home')
             ->output();
    }

    /**
     * @param $frame
     */
    function setup($frame){
        foreach ($this->components as $component){
            $frame->vueComponent($component);
        }
    }

}
