<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Core\Unicore;
use Neoan3\Frame\Ideahub;

class Home extends Unicore {
    private $components = ['profile','search','navbar','home'];
    function __construct() {
        new Ideahub();
    }

    function init(){
        $this->uni('ideahub')
             ->callback($this,'setup')
             ->hook('main','home')
             ->output();
    }

    /**
     * @param $frame
     */
    function setup($frame){
        foreach ($this->components as $component){
            $frame->vueComponent($component);
        }
    }

}
