<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Stateless;
use Neoan3\Frame\Ideahub;
use Neoan3\Model\UserModel;
use Neoan3\Core\Unicore;


class Profile extends unicore {
    private $components = ['profile'];
    function __construct() {
        new Ideahub();
    }

    /**
     * @param $obj
     *
     * @return mixed
     * @throws \Neoan3\Core\RouteException
     * @throws \Neoan3\Apps\DbException
     */
    function getProfile() {
        $jwt = Stateless::restrict('user');
        $user = UserModel::byId($jwt['jti']);
        return $user;
    }

    /**
     * @param $frame
     */
    function setup($frame){
        foreach ($this->components as $component){
            $frame->vueComponent($component);
        }
    }



}
