<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Stateless;
use Neoan3\Frame\Ideahub;
use Neoan3\Model\UserModel;
use Neoan3\Core\Unicore;


class Profile extends unicore {
    private $components = ['profile'];
    function __construct() {
        new Ideahub();
    }

    /**
     * @param $token
     *
     * @return mixed
     * @throws \Neoan3\Apps\DbException
     * @throws \Neoan3\Core\RouteException
     */
    function getProfile() {
        // TODO: Update get Profile
        $jwt = Stateless::restrict('user');
        $user = UserModel::byId($jwt['jti']);
        return $user;
    }

    function postProfile($obj){
        // TODO: create post method.
        echo '<pre>';
        print_r($obj);
    }


    /**
     * @param $frame
     */
    function setup($frame){
        foreach ($this->components as $component){
            $frame->vueComponent($component);
        }
    }



}
