<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Stateless;
use Neoan3\Frame\Ideahub;
use Neoan3\Model\UserModel;
//use Neoan3\Apps\Session;

class Profile extends Ideahub {
    /**
     * @param $obj
     *
     * @return mixed
     * @throws \Neoan3\Core\RouteException
     * @throws \Neoan3\Apps\DbException
     */
    function getProfile() {
        $jwt = Stateless::restrict('user');
        $user = UserModel::byId($jwt['jti']);
        return $user;
    }

    /*function postProfile($obj) {

    }*/
}
